version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    paths:
      - examples

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
